repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
-   repo: https://github.com/psf/black
    rev: '21.12b0'
    hooks:
    -   id: black
        args:
            - "-S"
            - "-l"
            - "120"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
    -   id: mypy
        args:
            - "--strict"
        exclude: "tests/*"
        additional_dependencies:
            - "types-PyYAML"
